### ISSUE TITLE
Generation is failing with ENOENT for wsdl2rest.readme.md when using built vsix

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-wsdl2rest#30]
in output, Log(Window):

```
[2019-02-26 09:52:30.611] [renderer1] [error] ENOENT: no such file or directory, stat 'c:\Users\Aurelien Pupier\.vscode\extensions\camel-tooling.vscode-wsdl2rest-0.0.3\src\wsdl2rest.readme.md': Error: ENOENT: no such file or directory, stat 'c:\Users\Aurelien Pupier\.vscode\extensions\camel-tooling.vscode-wsdl2rest-0.0.3\src\wsdl2rest.readme.md'
	at fs.statSync (fs.js:953:3)
	at Object.exports.wrapFsWithAsar.fs.statSync (ELECTRON_ASAR.js:295:16)
	at Object.statSync (C:\Users\Aurelien Pupier\.vscode\extensions\camel-tooling.vscode-wsdl2rest-0.0.3\node_modules\graceful-fs\polyfills.js:295:24)
	at checkStats (C:\Users\Aurelien Pupier\.vscode\extensions\camel-tooling.vscode-wsdl2rest-0.0.3\node_modules\fs-extra\lib\copy-sync\copy-sync.js:171:22)
	at checkPaths (C:\Users\Aurelien Pupier\.vscode\extensions\camel-tooling.vscode-wsdl2rest-0.0.3\node_modules\fs-extra\lib\copy-sync\copy-sync.js:183:31)
	at Object.copySync (C:\Users\Aurelien Pupier\.vscode\extensions\camel-tooling.vscode-wsdl2rest-0.0.3\node_modules\fs-extra\lib\copy-sync\copy-sync.js:25:20)
	at requirements.resolveRequirements.then.requirements (C:\Users\Aurelien Pupier\.vscode\extensions\camel-tooling.vscode-wsdl2rest-0.0.3\out\extension.js:228:20)
```

**Comment by apupier** [comment]
seems the code expects to have the files inside src folder but they are not available in vsix

**Comment by bfitzpat** [comment]
Able to reproduce this for sure. Worked around it by copying the file into a known location (jars directory) and accessing it there - https://github.com/camel-tooling/vscode-wsdl2rest/pull/31

Tested locally by generating a vsix file and seems to work.
