### ISSUE TITLE
Cannot use a wsdl online URL

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-wsdl2rest#36]
I tried to put https://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php?wsdl

and I had this error:

```
Executing Wsdl2Rest...
Retrieving document at 'file:/C:/Users/Aurelien%20Pupier/AppData/Local/Programs/Microsoft%20VS%20Code/https:/graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php%3Fwsdl'.
 
Error executing command
javax.wsdl.WSDLException: WSDLException: faultCode=OTHER_ERROR: Unable to resolve imported document at 'file:/C:/Users/Aurelien%20Pupier/AppData/Local/Programs/Microsoft%20VS%20Code/https:/graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php%3Fwsdl'.: java.io.FileNotFoundException: This file was not found: file:/C:/Users/Aurelien%20Pupier/AppData/Local/Programs/Microsoft%20VS%20Code/https:/graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php%3Fwsdl
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2291)
	at org.jboss.fuse.wsdl2rest.impl.WSDLProcessorImpl.process(WSDLProcessorImpl.java:94)
	at org.jboss.fuse.wsdl2rest.impl.Wsdl2Rest.process(Wsdl2Rest.java:79)
	at org.jboss.fuse.wsdl2rest.impl.Main.mainInternal(Main.java:60)
	at org.jboss.fuse.wsdl2rest.impl.Main.main(Main.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.io.FileNotFoundException: This file was not found: file:/C:/Users/Aurelien%20Pupier/AppData/Local/Programs/Microsoft%20VS%20Code/https:/graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php%3Fwsdl
	at com.ibm.wsdl.util.StringUtils.getContentAsInputStream(StringUtils.java:173)
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2270)
	... 12 more
```

is it an invalid URL that I'm using?

**Comment by bfitzpat** [comment]
Good question. I'll try it with the wsdl2rest utility itself and let you know.

**Comment by bfitzpat** [comment]
Two things - 
1. There was a problem with URL processing that forced the file: bit to be prepended to the url. I've fixed that in https://github.com/camel-tooling/vscode-wsdl2rest/pull/37
2. That WSDL does not seem to be supported by wsdl2rest - saw messages to that effect

I would try http://www.thomas-bayer.com/axis2/services/BLZService?wsdl or run the small SOAP-based web service included in the project here https://github.com/camel-tooling/vscode-wsdl2rest/tree/master/simplews

**Comment by bfitzpat** [comment]
Fixed
