### ISSUE TITLE
ClassNotFoundException: javax.xml.ws.Service

### ISSUE THREAD

**Issue by bawood** [camel-tooling/vscode-wsdl2rest#586]
I'm hoping to set up an integration using Camel with a Cisco Unified Communication Manager server's SOAP API.  I'm developing on a Debian Linux 11 desktop, using VSCode 1.60.2 and OpenJDK 8 from AdoptOpenJDK (I've also tried with the Debian default OpenJDK 11 with the same result).  I generated the camel setup with the camel-spring-boot maven archetype. After I run the wsdl2rest command and select the wsdl, it runs through all the services but fails with the following ClassNotFoundException, I've chopped out most of them for brevity.

```
Executing Wsdl2Rest...
Retrieving document at 'file:/home/abcdef/Dev/phones/Cisco/AXL_toolkit/schema/11.5/AXLAPI.wsdl'.
 
Retrieving schema wsdl:imported from 'AXLSoap.xsd', relative to 'file:/home/abcdef/Dev/phones/Cisco/AXL_toolkit/schema/11.5/AXLAPI.wsdl'.
 
Services: 
 
	AXLAPIService
 
	Port: AXLPort
	Binding: AXLPort
	PortType: AXLPort
 
	Operations: 
		Operation: addSipProfile
			Input: 
			Message: addSipProfileIn
			Part: :addSipProfile
 
				Params: 5.com/AXL/API/11.cisco.www.AddSipProfile {http://www.cisco.com/AXL/API/11.5}addSipProfile
 
			Output: 
 
			Message: addSipProfileOut
			Part: :addSipProfileResponse
 
				Params: 5.com/AXL/API/11.cisco.www.AddSipProfileResponse {http://www.cisco.com/AXL/API/11.5}addSipProfileResponse
			Faults: 
 
			Message: AXLError
 
			Part: :axlError
				Params: 5.com/AXL/API/11.cisco.www.AxlError {http://www.cisco.com/AXL/API/11.5}axlError

...<chopped>...

	SOAP Address URL: https://CCMSERVERNAME:8443/axl/
	SOAP Address URL: https://CCMSERVERNAME:8443/axl/

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (jar:file:/home/abcdef/.vscode/extensions/redhat.vscode-wsdl2rest-0.0.13/jars/wsdl2rest.jar!/BOOT-INF/lib/jaxb-impl-2.3.0.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
 
Error executing command
java.lang.NoClassDefFoundError: javax/xml/ws/Service
	at org.apache.cxf.tools.wsdlto.frontend.jaxws.JAXWSContainer.isJaxws22(JAXWSContainer.java:64)
	at org.apache.cxf.tools.wsdlto.frontend.jaxws.JAXWSContainer.getServiceTarget(JAXWSContainer.java:61)
	at org.apache.cxf.tools.wsdlto.frontend.jaxws.JAXWSContainer.validate(JAXWSContainer.java:68)
	at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.processWsdl(WSDLToJavaContainer.java:164)
	at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.execute(WSDLToJavaContainer.java:156)
	at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.execute(WSDLToJavaContainer.java:404)
	at org.apache.cxf.tools.common.toolspec.ToolRunner.runTool(ToolRunner.java:105)
	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:113)
	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:86)
	at org.jboss.fuse.wsdl2rest.impl.codegen.JavaTypeGenerator.execute(JavaTypeGenerator.java:36)
	at org.jboss.fuse.wsdl2rest.impl.Wsdl2Rest.process(Wsdl2Rest.java:92)
	at org.jboss.fuse.wsdl2rest.impl.Main.mainInternal(Main.java:60)
	at org.jboss.fuse.wsdl2rest.impl.Main.main(Main.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.ClassNotFoundException: javax.xml.ws.Service
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 21 more
 

Process finished. Return code 1.

```

**Comment by apupier** [comment]
based on the error, it sound slike a Java 11 is used in all cases.

Can you check:
- in File -> preferences -> Settings, if `java.home` is set? [reference](https://github.com/camel-tooling/vscode-wsdl2rest/blob/a91cf57ac8df7a84a7c28a7001093140a2955595/src/requirements.ts#L41)
- if JDK_HOME environment variable is set? [reference](https://github.com/camel-tooling/vscode-wsdl2rest/blob/a91cf57ac8df7a84a7c28a7001093140a2955595/src/requirements.ts#L45)
- if JAVA_HOME environment variable is set? [reference](https://github.com/camel-tooling/vscode-wsdl2rest/blob/a91cf57ac8df7a84a7c28a7001093140a2955595/src/requirements.ts#L49)
